Mount status and multiple connect support
tbutcaru/sshfs-manager pull request #5
Opened 2018-06-18 11:18 UTC by kukkjanos

Support check mount status and multiple connect with comma separated number

2018-06-19 04:59 UTC, tanasebutcaru requested changes

2018-06-19 04:59 UTC, tbutcaru commented on sshfs-manager.sh
> +            [USER_INPUT_ILLEGAL_SERVER_INDEX]='[SSHFS-MGR] Please select a valid comma separated number number(s) from the list. Exiting...\n'
`USER_INPUT_ILLEGAL_SERVER_INDEX` is not used anywhere in this file, I think it should replace `USER_INPUT_INVALID_SERVER_INDEX`.

Also, what do you think if we'd change the message into: 
> Please enter a valid number or multiple comma separated numbers from the list. Existing...\n

2018-06-19 04:59 UTC, tbutcaru commented on sshfs-manager.sh
> +	    mountPointStatus="(\e[1;91mOffline\e[0m)"
Let's add these two `mountPointStatus` into the `messages` dictionary.

2018-06-20 19:57 UTC, kukkjanos reviewed
I pushed a little fix!

2018-06-21 19:17 UTC, merged

2018-06-21 19:18 UTC, tbutcaru commented
Looking good. Merged!
Thank you :+1: